### PR TITLE
Resolve TravisCI build failure

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by mit-mit** [comment]
Actually, nevermind, I thought Dart www was hitting this issue that I just fixed on Flutter:
https://github.com/flutter/website/pull/622

But doesn't look like it's hitting on Dart anyway; closing.

**Comment by chalin** [comment]
Actually, we did hit that problem yesterday; I opened an issue over the firebase-tools: https://github.com/firebase/firebase-tools/issues/382

**Comment by chalin** [comment]
Let's give your fix a try here too.

**Comment by mit-mit** [comment]
kk, will wait and see if the two travis jobs pass before merging

**Comment by chalin** [comment]
(The deployment script only kicks in when a commit is over the `master` branch, so I needed to merge to see if it actually works.)

**Comment by chalin** [comment]
Yes, that worked. Thanks @mit-mit!

**Comment by kwalrath** [comment]
Sounds like I should make this change to https://github.com/dart-lang/site-www/blob/master/deploy/deploy-firebase.sh.

**Comment by chalin** [comment]
Yes, it will most likely be needed there too.

**Pull request merged**
