### PR TITLE
logo on the same level

### PR DESCRIPTION
**Pull request by Arhell**
before http://joxi.ru/1A5LEpXTndgeq2
after http://joxi.ru/nAypl8btYJp7W2

### CODE REVIEW

**Comment by kwalrath** [comment]
Thanks for the PR!

Can you tell me which browser you're using? On Chrome (on my Mac), the baselines on webdev.dartlang.org look fine:

image

With your change, the "for the web" looks too low:

image

**Comment by Arhell** [comment]
@kwalrath thanks you, yes Chrome and mac)
I update PR, better result
Check on mac and windows chrome

**Comment by Arhell** [comment]
@kwalrath  thank you for post
Sure
before http://joxi.ru/eAOE81RfxY658m
after http://joxi.ru/bmoRyV0CxK7z9r
But a change on 1px it was 1.3 margin-bottom
This on mac

**Comment by Arhell** [comment]
before 
joxi_screenshot_1547055665074
after 
joxi_screenshot_1547055726350

on windows

**Comment by kwalrath** [comment]
I've restaged https://kw-webdev-dartlang-2.firebaseapp.com. ptal, everyone who cares about pixels... :)

**Comment by chalin** [comment]
Honestly, I'd rather we not play around with this. It took time to tune things before, and we're aware that it isn't perfect, but IMHO it is good enough. There are lots of cases to consider, and we don't really have the time atm to review all of them again. E.g., the latest changes result in this view:

> screen shot 2019-01-09 at 14 28 15

@Arhell - I appreciate the effort, but this simply isn't a priority atm.

So, I'd vote for status quo. (My 2 cents)

**Comment by kwalrath** [comment]
Wow, it never occurred to me that a chance to the top would have that effect. Thanks for your work, @Arhell, but I'm reluctantly closing this PR.

**Pull request closed without merging**
