### PR TITLE
Map v4 site og:image to v5 image

### PR DESCRIPTION
**Pull request by chalin**
Contributes to #1567, #1690

Staged at https://angulardart-org-dev.firebaseapp.com. Try:

- https://angulardart-org-dev.firebaseapp.com/assets/angulardart.png?4=
- https://angulardart-org-dev.firebaseapp.com/assets/dart-webdev-logo.png?4=

### CODE REVIEW

**Comment by kwalrath** [comment]
Will this change take care of this issue in the future, too?

**Comment by chalin** [comment]
> Will this change take care of this issue in the future, too?

Yes, this shouldn't be an issue moving forward.

**Comment by chalin** [comment]
Merging now so that we can get this fixed ASAP.

**Comment by chalin** [comment]
Once this is deployed, I'll force a refresh of the og:image on https://developers.facebook.com/tools/debug/.

**Pull request merged**
