### PR TITLE
Copy edit: angular/guide/testing/component

### PR DESCRIPTION
**Pull request by jenapp**
Still possible issues with the formatting of the package list at the top, but out of time.

### CODE REVIEW

**Comment by kwalrath** [comment]
I haven't heard from @jenapp, so it looks like @sarahmaddox or I will need to fix the package list.

**Comment by jenapp** [comment]
Huge apologies Kathy!

I’ve been on leave and then have been flat out since my return. No excuses for not responding to your previous email at least. 

I’m happy to complete the edits, but I probably wont be able to get to it until next week. Though I’m feeling rather guilty at the moment, so will try and have look this afternoon.

If I don’t get to it today, is next week ok?

Regards,


Jen

 <http://www.inomial.com/>

 <http://www.inomial.com/>Jennifer Appleby <mailto:jennifer@inomial.com> • tech writer
Inomial Pty Ltd • Automatic Billing <http://www.inomial.com/>
p +61 3 9663 3554 • m 0413 693 429

 <http://www.linkedin.com/company/inomial-pty-ltd> <https://www.facebook.com/Inomial> <https://twitter.com/inomial>
 <https://twitter.com/inomial>

**Comment by kwalrath** [comment]
No worries, Jen! Next week would be fine. Thanks!

**Comment by jenapp** [comment]
Hi Kathy,

Have submitted edits for the package list. 

When I review the changes it appears that links aren’t being rendered properly. I’m new to GitHub so I don’t know if that’s a limitation with the preview or I’ve done something wrong! If it’s me, could you let me know how to fix it and avoid it in future please?

Thanks,
Jen

 <http://www.linkedin.com/company/inomial-pty-ltd> <https://www.facebook.com/Inomial> <https://twitter.com/inomial>
 <https://twitter.com/inomial>

**Comment by kwalrath** [comment]
I suspect it's a GitHub limitation (or, more precisely, an issue caused by our site's inability to be rendered by GitHub). I'll check your changes. Thanks!

**Pull request merged**
