### PR TITLE
[4-dev] upgrade to 4.0.0-alpha+2

### PR DESCRIPTION
**Pull request by chalin**

### CODE REVIEW

**Comment by kwalrath** [comment]
You'll also update tutorial/toh-pt5 to talk about the angular_router package, correct?

**Comment by chalin** [comment]
Yes. I'm just trying to get all tests to pass first.

**Comment by chalin** [comment]
> You'll also update tutorial/toh-pt5 to talk about the angular_router package, correct?

Done.

**Comment by chalin** [comment]
Component tests have been disabled since they are not working under alpha-2; as a consequence, Travis reports green. Merging now into 4-dev.

**Pull request merged**
