### PR TITLE
too much reliance on WebStorm

### PR DESCRIPTION
**Pull request by bwfrieds**
Clarified and simplified instructions for the command line.   Always favor the command line over an IDE.

### CODE REVIEW

**Comment by bwfrieds** [comment]
I signed it.

**Comment by chalin** [comment]
Thanks for expressing your concern and submitting a PR @bwfrieds. Now for some context ...

Not too long ago we reworked the [Get started](https://webdev.dartlang.org/guides/get-started) page to present command line first, and make command line instructions more complete -- in particular, instructions are given to install `webdev`. First, I'd rather similarly rework the [Setup for development](https://webdev.dartlang.org/angular/guide/setup) page before making changes to [The Starter App](https://webdev.dartlang.org/angular/tutorial/toh-pt0) page (which refers to **Setup for development**). 

@kwalrath WDYT?

**Comment by kwalrath** [comment]
Agreed, @chalin

**Comment by bwfrieds** [comment]
> @bwfrieds, are you willing to rework the [Setup for development](https://webdev.dartlang.org/angular/guide/setup) page?
> 
> If not, I'll close this PR and file an issue to update that page, followed by [The Starter App](https://webdev.dartlang.org/angular/tutorial/toh-pt0) (with a reference to the work in this PR).

Um, I'm probably not the right person for that.

**Comment by kwalrath** [comment]
> Um, I'm probably not the right person for that.  

:) OK, I'll take of it. Thanks very much for your work and for bringing this to our attention!

**Pull request closed without merging**
