### PR TITLE
[ng] define $brand-secondary color scheme

### PR DESCRIPTION
**Pull request by chalin**
Have `$brand-primary` match main Dart site; i.e., be blue.
Keep turquoise as `$brand-secondary` color scheme to be used only in
homepage banner and as main nave menu item hover color.

Addresses issues from #183 (I'll let @kwalrath decide if this addresses _all_ aspects of 183).

Homepage stays the same. Here is the new look for a typical Angular page (note the main nav entry text and hover color):
screen shot 2016-12-05 at 5 44 23 pm

It used to be:
screen shot 2016-12-05 at 5 44 36 pm

### CODE REVIEW

**Comment by chalin** [comment]
cc @ericjim

**Comment by kevmoo** [comment]
Staged somewhere?

**Comment by chalin** [comment]
Sry, I got used to auto-staging :). It is on the dev site.

**Comment by chalin** [comment]
@kevmoo @kwalrath - I added screen shots to the original PR comment.

**Comment by kwalrath** [comment]
Looks great to me. I'm going to merge this, since it's a big improvement on the current site. @kevmoo if you have any feedback, we can address that in another PR.

And yes, this fixes #183. :)

**Pull request merged**
