### PR TITLE
Add optional .html extension to redirect source urls.

### PR DESCRIPTION
**Pull request by msmorgan**
Some Google results about AngularDart still have a .html extension on
the URL. This commit adds .html to each of the redirect source blobs, so
that the redirect will happen with or without the extension.

### CODE REVIEW

**Comment by msmorgan** [comment]
I was not able to test locally whether this works. Firebase complained that I don't have permission for "firebase.projects.get".

**Comment by mit-mit** [comment]
Thanks, LGTM

**Comment by mit-mit** [comment]
@msmorgan this has landed, and from my sporadic testing appears to be working. Can you try with the links you had seen broken before?

**Comment by msmorgan** [comment]
@mit-mit Thank you! I tried with the links that were broken before, and they're working now.

**Pull request merged**
