### PR TITLE
chore: redirect `angular2.common/**` to the library page

### LINKED ISSUE #877: Site search still generates URLs to angular/api/angular2.common which are 404s
URL: https://webdev.dartlang.org/angular/api/angular2.common/NgClass-class
Expected page: https://webdev.dartlang.org/angular/api/angular2/NgClass-class

The bad URL was generated from the site search

see 1st result:
https://webdev.dartlang.org/search?cx=011220921317074318178%3Ata2gkewbtuu&ie=UTF-8&hl=en&q=ngClass

### PR DESCRIPTION
**Pull request by chalin**
Redirect all `angular2.common/**` API entries to the angular2.common library page: https://webdev.dartlang.org/angular/api/angular2.common/angular2.common-library

From there, readers will find their entries with proper links into the `angular2` library. E.g. `NgIf` refers to https://webdev.dartlang.org/angular/api/angular2/NgIf-class

Followup to https://github.com/dart-lang/site-webdev/pull/853#issuecomment-316846338.

Fixes #877.

Staged at https://angulardart-org-dev.firebaseapp.com

Here is an example of a link that will trigger the redirect: https://angulardart-org-dev.firebaseapp.com/angular/api/angular2.common/COMMON_PIPES-constant

### CODE REVIEW

**Comment by kwalrath** [comment]
We'll need to add another redirect once 4.0 ships, right? I guess this would be part of #880.

**Comment by chalin** [comment]
Right, we'll need to add other redirect(s) for 4.0.

I thought that #880 was just about the _preparation_, which is what the recent sitemap PRs have been doing. If so, I'd close #880, and open another issue or add a bullet to #670. If not, then maybe change the title of #880?

**Comment by kwalrath** [comment]
Whichever way makes sense to you is fine by me.

**Comment by chalin** [comment]
I've added a bullet to #670.

**Comment by chalin** [comment]
(In which case, can you close #880?)

**Pull request merged**
