### PR TITLE
Update get-started.md

### PR DESCRIPTION
**Pull request by anders-sandholm**
I was missing this info when going through the process.

### CODE REVIEW

**Comment by chalin** [comment]
The information about paths is given in the [Installing Dart on Mac, "Installation locations" section](https://www.dartlang.org/install/mac#installation-locations):
> Many tools, such as editors, ask you to specify the Dart SDK installation directory and the location of Dartium. Homebrew uses the following locations, where you replace HOMEBREW_INSTALL with the the homebrew installation directory (which you can get using brew --prefix):
> 
> - SDK directory: HOMEBREW_INSTALL/opt/dart/libexec
> - Dartium: HOMEBREW_INSTALL/opt/dart/Chromium.app

Perhaps we can point readers to that section, rather than mention "caveats" (which my confuse some readers who don't pay attention to the output :).

@kwalrath, WDYT?

For the record, here is sample output from homebrew:
```
==> Upgrading dart-lang/dart/dart --with-dartium
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/1.22.1/sdk/da
######################################################################## 100.0%
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/1.22.1/dartiu
######################################################################## 100.0%
==> Caveats
Please note the path to the Dart SDK:
  /opt/homebrew/opt/dart/libexec

--with-dartium:
  To use with IntelliJ, set the Dartium execute home to:
    /opt/homebrew/opt/dart/Chromium.app
==> Summary
🍺  /opt/homebrew/Cellar/dart/1.22.1: 1,350 files, 403.5M, built in 38 seconds
==> Upgrading nvm 
==> Using the sandbox
==> Downloading https://github.com/creationix/nvm/archive/v0.33.1.tar.gz
==> Downloading from https://codeload.github.com/creationix/nvm/tar.gz/v0.33.1
######################################################################## 100.0%
```

**Comment by kwalrath** [comment]
Maybe I should add something similar to/for all the sections, since you need the path no matter which OS you're using.

**Comment by anders-sandholm** [comment]
Either way is fine with me. All I know is I was trying to follow the guide and wasn't sure what to do at "If the path fields don't have values, enter them."

**Comment by kwalrath** [comment]
Sorry for the delay... I'll work on this soon.

**Comment by kwalrath** [comment]
Closed in favor of #446.

**Pull request closed without merging**
