### PR TITLE
Streamline page footer and add build info

### LINKED ISSUE #1003: Add build info to deployed site
E.g., [angular.io](https://angular.io/) has something like this at the bottom of each page:

> Version 4.3.7-build.34359+sha.dfe2bad

### PR DESCRIPTION
**Pull request by chalin**
Fixes #1003, #1007 

The new footer looks like this

screen shot 2017-09-27 at 13 17 44

- The Angular version links to the version page.
- The build number links to the build page.
- The sha links to the commit.

Staged at https://angulardart-org-dev2.firebaseapp.com

### CODE REVIEW

**Comment by kwalrath** [comment]
/cc @kevmoo @filiph @Sfshaza

I'm a little nervous about removing all those links, yet I like the streamlined look and doubt most people were using the links. Let me see if I can get some analytics to prove that.

The bottom line seems unclear, with its mix of AngularDart versioning (already covered elsewhere) and site-webdev build/commit info. Let's chat about this.

**Comment by kwalrath** [comment]
For usability/accessibility's sake, the icons at the bottom should be farther apart.

**Comment by chalin** [comment]
Following Kathy's feedback, here is the new proposed (and further simplified) footer:

> screen shot 2017-09-27 at 16 26 41

The build icon links to a separate build information page. (Of course, I can remove that icon from the footer if you don't want it on each page, but it can be useful when filing bugs to be able to identify the build.)

> screen shot 2017-09-27 at 16 27 56


Staged at https://angulardart-org-dev3.firebaseapp.com

**Comment by kwalrath** [comment]
Removing the build info page makes sense, unless we want to move some/all of the build info from site-webdev to that page.

**Comment by kevmoo** [comment]
Build: instead of a link, just embed it in the page somewhere so folks can
find it in the source?

**Comment by chalin** [comment]
@kevmoo - any objections to keeping the build icon (and link)?

**Comment by kevmoo** [comment]
> @kevmoo - any objections to keeping the build icon (and link)?

Not really.

**Comment by chalin** [comment]
Btw, I'll close #1008 if/once this PR is accepted, because part of the reason I created #1008 was to get the Angular version on the Get Started page (which this PR achieves).

**Comment by filiph** [comment]
Do you want to add one other link, [Community](https://www.dartlang.org/community) ?

That's what I look for in footers — ways to connect.

**Comment by chalin** [comment]
@filiph: done. How about the following? I added a people icon with a link to our [community](https://webdev.dartlang.org/community) page (iPhone 5 screenshot):
> screen shot 2017-09-28 at 06 52 16

**Comment by filiph** [comment]
I'm not sure if I would understand the icon but I that's fine, I'd hover over it.

I'm looking at other footers (golang, typescript, vue, angularjs, angular) and only one of them has a community link at the bottom (angular). So it's probably just me.

Anyway, LGTM, thanks for making the site look this slick!

**Comment by chalin** [comment]
In that case I'd vote to drop the community icon (and link). Users can always access the community page from the sidenav.

**Comment by kwalrath** [comment]
I asked on gitter, and no one objected. Let's try the new footer and see if anyone objects.

In the meantime, I'll look into adding some of the ex-footer links to pages where people are most likely to need them.

**Comment by chalin** [comment]
Ok, nice. Can you approve the PR pls?

**Comment by kwalrath** [comment]
Approved via hangout. :)

**Pull request merged**
