### PR TITLE
[acx] basic landing page

### LINKED ISSUE #549: [acx] create an index page for /components

### PR DESCRIPTION
**Pull request by chalin**
Fixes #549

Staged at https://angulardart-org-dev.firebaseapp.com/components

### CODE REVIEW

**Comment by kwalrath** [comment]
Could you restage this?

**Comment by chalin** [comment]
Done. Now staged at https://angulardart-org-dev.firebaseapp.com/components

**Comment by kwalrath** [comment]
Ah, right! I remember now what the issue was... It looks/acts too much like the AngularDart homepage. Let's think of what would be good things to talk about or show or link to:

Discussion:
* Growing subset of a large, productive, stable set of components used internally at Google.
* Officially supported browsers: The last two versions of Chrome, Edge, Firefox, and Safari.
  * IE not supported.

Links:
* Codelab: https://webdev.dartlang.org/codelabs/angular_components
* AngularDart: https://webdev.dartlang.org/angular
* Component gallery: https://dart-lang.github.io/angular_components_example/
* ? Repo: https://pub.dartlang.org/packages/angular_components
* ? Pub page: https://pub.dartlang.org/packages/angular_components
* ? material.io

Images: Component gallery screenshot?

**Comment by chalin** [comment]
I was initially just looking for a quick placeholder (to replace the redirect), but you are right, we can adjust it further now too. I'll make a second pass soon (unless you want to give it a try).

**Comment by kwalrath** [comment]
Go ahead if you're inspired.

**Comment by kwalrath** [comment]
See #636 for my try at this.

**Comment by chalin** [comment]
Superseded by #636

**Pull request closed without merging**
