### PR TITLE
toh component tests - add html file for in-browser testing

### PR DESCRIPTION
**Pull request by chalin**

### CODE REVIEW

**Comment by kevmoo** [comment]
@chalin why is this needed? Are you going to add html content later?

**Comment by chalin** [comment]
This is a "test debugging" feature I will be describing in the new testing page. It allows us to view the tests are they are running in the browser.

**Comment by chalin** [comment]
Awaiting feedback from @matanlurey concerning the "EXCEPTION: Bad state: Cannot fire new event. Controller is already firing an event" issue (details sent via email).

**Comment by chalin** [comment]
Also awaiting your feedback on this PR @matanlurey. Thanks.

**Comment by chalin** [comment]
Since this has been approved, and it is working -- despite the spurious "EXCEPTION: Bad state: Cannot fire new event. Controller is already firing an event" issue -- I'm going to merge now so that it can be easier to reproduce for @matanlurey.

**Pull request merged**
