### PR TITLE
Cheatsheet bootstrap -> runApp() + static DI

### PR DESCRIPTION
**Pull request by chalin**
- This PR replaces the _Bootstrapping_ cheatsheet subtable with a _Run app and compile-time injector generation_ subtable.

  The new code excerpts need to be larger (e.g., because of the template imports, without which I doubt a single-line cheatsheet `runApp()` entry would make sense).

- All code snippets are excerpt from the quickstart app.

- The new subtable illustrates how I think the rest of the cheatsheet should be restyled:
  - Code excerpts, including the import statement in the table header, in the right column
  - Commentary on the left.

  The code column is given more space (65%)

Contributes to #1483, #1495

Staged at https://angulardart-org-dev2.firebaseapp.com/angular/cheatsheet

---

New cheatsheet entries:

screen shot 2018-04-17 at 18 01 30

Old cheatsheet entries:

screen shot 2018-04-17 at 18 02 26

### CODE REVIEW

**Comment by kwalrath** [comment]
Interesting! Making the excerpts longer seems fine to me, and it'd make me very happy to have tested excerpts. I also like having the highlighted code. (Didn't we have that before?)

Some questions/comments:

1. Why switch the code to the right? Having the `import` statement for the whole group be above the other code seems confusing (especially in the bootstrapping code, where you have additional imports). I rather like having all the code on the left, since that seems like the most important part of the page.

2. Why have such a long name for what was formerly Bootstrapping? Do you think it'd be confusing to still call it **Bootstrapping**? (People might search for that, and the [angular.io cheatsheet](https://angular.io/guide/cheatsheet) still uses that term.)

3. What can we do to make the table take up the whole width of the page? There's a lot of wasted space on the right when the window's wide.

4. I don't like having bold font in the descriptions. It feels like bold font should be reserved for the table heads, so it's easy to scan for the next table.

**Comment by chalin** [comment]
Here are some answers. I'll tackle changes tomorrow.

> 1. Why switch the code to the right? ...

It just looked strange to have a wider code column on the left. I don't mind putting it back on the right.

> 2. Why have such a long name for what was formerly Bootstrapping?

I wasn't sure about that one. I'm ok with keeping "bootstrapping". It's really about "App launching", but that seemed like a strange title to me.

> 3. What can we do to make the table take up the whole width of the page? There's a lot of wasted space on the right when the window's wide.

I think that there is a global maximum width because it can be difficult to read very wide tables. I can adjust that.

> 4. I don't like having bold font in the descriptions. It feels like bold font should be reserved for the table heads, so it's easy to scan for the next table.

Ok.

**Comment by chalin** [comment]
> Having the `import` statement for the whole group be above the other code seems confusing

It isn't always an import. Regardless, again it seemed strange to have that import inside the narrow column.

Based on my comments above, let me know if your preferences have changed

**Comment by chalin** [comment]
Done:

- [x] Show code in the left column
- [x] Revert to Bootstrapping title
- [x] Drop max table width
- [x] Drop bold font in the descriptions

Staging server refreshed: https://angulardart-org-dev2.firebaseapp.com/angular/cheatsheet

**Comment by chalin** [comment]
Great! I'll convert the other cheatsheet tables over time (starting with the router table).

**Pull request merged**
