### PR TITLE
Update user-input.jade

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by kwalrath** [comment]
Thanks, @a14n! @chalin can we make changes like this (finally!) or do we still have tendrils of ng.io stopping that?

**Comment by chalin** [comment]
No strings attached for the files under `src/angular` with the exception of the files below `src/angular/_jade` (which may require a little extra care).

Thanks for the PR Alexandre. Note that I'd go further any change:
> We cast ...

to

> We declare ...

since there is no casting involved.

**Comment by a14n** [comment]
@chalin updated

**Comment by a14n** [comment]
humm perhaps _We declare the `$event` **with** a `dynamic` type_ would be better ?

**Comment by chalin** [comment]
Ah, right, that does need some tweaking. I'd propose:
> We declare the type of `$event` as `dynamic`, which means ...

**Comment by kwalrath** [comment]
"casting" is mentioned later, too.

But actually... why are we using `dynamic`? I thought we never recommended that for user code, and used `Object` instead.

**Comment by chalin** [comment]
Yes, casting is mentioned again, but I was aiming to just get this simple fix in, with the objective of making a full pass later on. But if you prefer that it be fixed in one go, that is ok with me.

It feels as if this version of the page was influenced by the TS counterpart. I think that the use of `dynamic` is ok here as it covers the scenario where we're just not bothering to think about what the type should be.

**Comment by kwalrath** [comment]
Full pass later on SGTM.

**Pull request merged**
