### PR TITLE
crushed pngs

### PR DESCRIPTION
**Pull request by kevmoo**
Saved ~250k

### CODE REVIEW

**Comment by kwalrath** [comment]
@chalin perhaps we can contribute this PNGs to angular.io.

**Comment by chalin** [comment]
Yes, certainly. Shall I back propagate this optimization?

**Comment by kwalrath** [comment]
Sure, if you have the time. Alternately, just let them know about it. :)

**Comment by kevmoo** [comment]
Ya'll are very nice 😄

**Pull request merged**
