### PR TITLE
[4-dev] fix and enable component tests

### PR DESCRIPTION
**Pull request by chalin**

### CODE REVIEW

**Comment by kwalrath** [comment]
We REALLY need to add this to the changelog!

**Comment by chalin** [comment]
Did you want to continue adding to the changelog or did you want me to do it?

**Comment by kwalrath** [comment]
Either way works for me. I just don't want to forget things. Maybe we should have an AddToChangelog label.

**Comment by chalin** [comment]
> We REALLY need to add this to the changelog!

Done,  #939. (I walked through the diff of the master and 4-dev branches.)

**Pull request merged**
