### PR TITLE
Reinstate template-syntax component tests

### LINKED ISSUE #1834: pub upgrade fails for template-syntax
Due to transitive package [dependency incompatibilities with pageloader](https://github.com/google/pageloader/issues/158#issuecomment-432419824), the template-syntax example can't be built:

```nocode
Because code_builder >=0.1.3 <3.1.2 requires SDK version >=1.9.1 <2.0.0-∞ and code_builder >=3.1.2 <3.1.3 depends on built_collection >=1.0.0 <4.0.0, code_builder >=0.1.3 <3.1.3 requires built_collection >=1.0.0 <4.0.0.
And because code_builder >=3.1.3 depends on built_value ^6.0.0, code_builder >=0.1.3 requires built_value ^6.0.0 or built_collection >=1.0.0 <4.0.0.
And because angular >=5.0.0-beta+1 depends on code_builder ^3.0.1 and pageloader >=3.0.0-beta depends on built_value ^5.1.0, if pageloader >=3.0.0-beta and angular >=5.0.0-beta+1 then built_collection >=1.0.0 <4.0.0.
And because template_syntax depends on angular_components ^0.10.0 which depends on built_collection ^4.0.0, pageloader >=3.0.0-beta is incompatible with angular >=5.0.0-beta+1.
So, because template_syntax depends on both angular ^5.0.0 and pageloader ^3.0.1, version solving failed.
```

### PR DESCRIPTION
**Pull request by kwalrath**
Contributes to #1834

### CODE REVIEW

**Comment by chalin** [comment]
Tests are failing on Travis:

- https://travis-ci.org/dart-lang/site-webdev/jobs/470637795
- https://travis-ci.org/dart-lang/site-webdev/jobs/470637798

 Are tests passing locally for you?

**Comment by kwalrath** [comment]
I didn't try them locally. I'll do that now.

**Comment by chalin** [comment]
All tests are passing \o/. You might want to change the opening comment from "Fixes #1834" to "Contributes to #1834"

**Comment by kwalrath** [comment]
e2e test is failing, so I've disabled it and will file an issue.

**Pull request merged**
