### PR TITLE
Examples: deploy ACX gallery under webdev site

### PR DESCRIPTION
**Pull request by chalin**
This fetches the built version of the gallery from https://github.com/dart-lang/angular_components_example/tree/gh-pages.

Staged at https://angulardart-org-dev.firebaseapp.com/examples/component-gallery

Contributes to  #1533 

cc @kwalrath @nshahan

### CODE REVIEW

**Comment by kwalrath** [comment]
I like it! If @nshahan and @tedsander are good with it, I say we ship it.

We should add an index page or redirect (could be in a separate PR) so that https://angulardart-org-dev.firebaseapp.com/examples isn't a 404.

**Comment by nshahan** [comment]
@chalin What would the deploy process be like on every update? 

@kevmoo what would this mean for the analytics?

**Comment by kevmoo** [comment]
> @kevmoo what would this mean for the analytics?

We should update the analytics bits in the samples to match the webdev site.

Wonder if @chalin can do magic w/ a string-replace here...

**Comment by chalin** [comment]
Sure: let me know what needs to be replaced, and what the replacement is.

**Comment by chalin** [comment]
@nshahan - btw, if we host the ACX gallery on webdev, the app will be able to switch to using the **path location strategy**.

So who's thumbs-up are we waiting on?

**Comment by chalin** [comment]
> I don't understand the context here. What does hosting the gallery on webdev solve?

A flip question is: what do we have to gain by hosting on **GH-pages** where:

- You are forced to use the dev-mode HashLocationStrategy
- You can't setup redirect rules when the API changes, etc.

Firstly, understand that there is **no extra effort required on your part**. You can continue to build and deploy the ACX gallery to the current repo.

Hosting on webdev has a number of advantages, the main ones being the following:

- UX: **webdev.dartlang.org** becomes the **central point** for all things _Angular / Dart for the Web_.

  AngularTS's main site is https://angular.io and you'll find the material design app at https://material.angular.io.

- The webdev site is versioned:

  - Stable is at https://webdev.dartlang.org and, 
  - Dev version is at https://webdev-dartlang-org-dev.firebaseapp.com
  - (We have an archive version for v3, etc)

  As has been mentioned elsewhere, we also **need the ACX gallery to be versioned**. Hosting it on webdev (and its companion stable/dev sites) solves this problem in part.

- You can use PathLocationStrategy, encode rewrite/redirect rules, ... .

(If you were asking about the original context for this PR, it is #1533.)

**Comment by TedSander** [comment]
I do not want to change to PathLocationStrategy. It makes internal deployment harder, and it makes development A LOT harder.

**Comment by kwalrath** [comment]
I'm going to close this, since it's been around for ages with no progress. @chalin, we can talk about this tomorrow, if that works for you.

**Pull request closed without merging**
