### PR TITLE
Show Angular version in Get Started page header

### LINKED ISSUE #1006: Add Angular version to Get Started page header

### PR DESCRIPTION
**Pull request by chalin**
Fixes #1006 and tweaks a few scripts/directives too.

Best reviewed by [ignoring whitespace](https://github.com/dart-lang/site-webdev/pull/1008/files?w=1).

- Staged at https://angulardart-org-dev.firebaseapp.com/guides/get-started
- Contrast with https://webdev.dartlang.org/guides/get-started

### CODE REVIEW

**Comment by kwalrath** [comment]
I'm not sure about branding the Get Started page, which doesn't require Angular until step 4, as Angular.

@filiph & @wmleler do you have an opinion?

**Comment by chalin** [comment]
It's step 4 because most of the steps before that are setup. Regardless, after having completed this page, readers will have build their first AngularDart + Angular Components app.  So the "branding" feels appropriate to me.

But I'm not wed to the idea, but I am hoping that we an find a way to get the Angular version visible on (practically) every page of the site ... as is done at angular.io: e.g., https://angular.io/guide/quickstart (the current version is in the sidenav).

**Comment by kwalrath** [comment]
Patrice, is there anything we need to save from this PR, or should we just close it?

**Comment by chalin** [comment]
It can just be closed.

**Pull request closed without merging**
