### PR TITLE
[ng] About side nav selection fix

### LINKED ISSUE #518: "About" stays selected in sidenav
If I go to an Angular page on my local server (or to a staged page such as https://angulardart-org-dev2.firebaseapp.com/angular/glossary), the word **About** is always bold, no matter which page you're on. Not sure when this started, but it's not this way on the external site (https://webdev.dartlang.org/angular/glossary, e.g.).

### PR DESCRIPTION
**Pull request by chalin**
Fixes #518

### CODE REVIEW

**Comment by kwalrath** [comment]
Thank you!

I happened to notice another small issue, but it's not new. (But if you're in the fixing mood, it'd be nice to fix.)

When you open a submenu, that submenu is bold even though you haven't moved to its section. For example, when you're on the **About** page and click the doohickey to the right of **Tutorial**, both **About** and **Tutorial** are bold, even though you're still on the About page:

image

**Comment by chalin** [comment]
Thanks for the approval.

As for the side-nav group becoming bold when open, I had thought that that was a feature :).

**Comment by kwalrath** [comment]
Yeah, that code didn't look easy to figure out. But I thought you might be in that headspace. No worries. :)

**Comment by chalin** [comment]
I've opened #525 to track the issue in case we decide to get to it at some point (though my hope is that we'll just change the menu system :).

**Pull request merged**
