### PR TITLE
Upgrade to 4.0.0

### PR DESCRIPTION
**Pull request by chalin**
This upgrades all examples, except for the ACX codelab which will follow shortly.

### CODE REVIEW

**Comment by kevmoo** [comment]
LGTM – @kwalrath ?

**Comment by chalin** [comment]
> We should put something about the inputs change in the changelog, but that can be a separate PR.

I'm doing that now.

**Comment by chalin** [comment]
Changelog updated via #988

**Comment by chalin** [comment]
Travis is green. Merging.

**Pull request merged**
