### PR TITLE
Improve links for /tools/build_runner

### LINKED ISSUE #1451: Add a redirect from master /tools/build_runner to dev tools/build_runner
So we can have a long-lived link

### PR DESCRIPTION
**Pull request by kwalrath**
Create a temporary redirect so we can tell people to look at webdev.dartlang.org/tools/build_runner even before we switch webdev to Angular 5.

Fixes #1451.

### CODE REVIEW

**Comment by kwalrath** [comment]
Don't review yet... I'll address #1450 here too.

**Comment by kwalrath** [comment]
OK, it's ready now. Staged at:

https://kw-webdev-dartlang-1.firebaseapp.com/dart-2
https://kw-webdev-dartlang-1.firebaseapp.com/tools/build_runner

**Comment by kevmoo** [comment]
Well, the links on `https://webdev-dartlang-org-dev.firebaseapp.com/tools/build_runner` to the readme will also need to be updated, but that's the other branch...

**Comment by kwalrath** [comment]
Yep, the -dev fix is in #1453. I assigned that one to Patrice, but you're welcome to take a look.

**Pull request merged**
