### PR TITLE
Updated design: logos, colors, etc

### LINKED ISSUE #1569: Update design: logos, colors, etc
- [x] Main logo: opt for **one** of the following
  - [ ] Create a "Dart for the web" logo lockup
  - [x] Base Dart logo w/o lockup
- [x] favicon: opt for **one** of the following
  - [ ] New "Dart for the web" logo
  - [x] Base Dart logo
- [x] Social media shared images: opt for **one** of the following
  - [ ] "Dart for the web", **or**
  - [x] Dart logo as og_image #832 
- [x] Frontpage:
  - [x] Color scheme: get agreement on new colors to use (no more green :)
  - [x] "Angular love" image update
  - [x] Dart icon in "Open DartPad"
  - [ ] Time permitting, address: Frontpage edits #1577
- [x] Nav bars
  - [x] Mainnav:
    - [x] Logo update
    - [x] Switch to dartlang.org color scheme
    - [x] Update dropdown color scheme
    - [x] Ensure nav has no glitches at media query transition sizes (for mobile in particular).
  - [x] Sidenav
     - [x] Logo update
- [x] Footer color like flutter.io
- [ ] All other site pages: check for uses of old logo and switch to new ones (including page-local image folders)
- [x] Examples:
  - [x] Update favicon in boilerplate folder
  - [x] Scan for use of all logos in example project folders
  - [x] ACX codelab has a few copies of the old "Angular love" image.
- [ ] Ensure submodule branch was merged and that this PR points to the updated master.

Related:
- https://github.com/dart-lang/site-www/issues/651
- https://github.com/dart-lang/site-www/pull/830

### PR DESCRIPTION
**Pull request by chalin**
Staged at https://angulardart-org-dev3.firebaseapp.com

Fixes #1569

cc @filiph @kevmoo

### CODE REVIEW

**Comment by kevmoo** [comment]
I want to get rid of that entire "Stable & maintained" row – but we can do
that in a follow-up

**Comment by kevmoo** [comment]
Ditto w/ the example screenshot that references Angualr2 – can be done in a follow-up

**Comment by chalin** [comment]
Maybe a better opening example would be nice too (even if it means that we aren't using DartPad).

**Comment by chalin** [comment]
@kevmoo - I've created #1577 to track the improvements we want to make to the front page.

**Comment by chalin** [comment]
@kevmoo - the updates that you requested in #1577 have been done. See the refreshed staging server: https://angulardart-org-dev3.firebaseapp.com

**Comment by kevmoo** [comment]
Awesome! Can we switch the favicon to the dart one, too?

**Comment by kwalrath** [comment]
Is it a problem that www.dartlang.org and this new look are so similar? We added the black bar and more colors because we were trying to make webdev look different. www was going for a subdued look.

Maybe we should use the globe icon for webdev?

**Comment by chalin** [comment]
Good question: should we use the [globe](https://github.com/chalin/site-shared-dartlang/blob/master/src/_assets/images/web/icon/globe-940.png) or the Angular icon for the favicon?

Also, I can make the main nav dark again (to match the brand-primary blue of the footer).

**Comment by chalin** [comment]
> Is it a problem that www.dartlang.org and this new look are so similar?

The logos are different: webdev has "Dart for the web". After some experimentation, I've come to the conclusion that it would be difficult (with the current logo and color scheme), to have a dark main nav.

I've main the main nav border a bit sharper. That with the dark blue "for the web", should be enough of a difference for now. WDYT?

**Comment by kwalrath** [comment]
@kevmoo Note that these changes are to the v5 site, not the current webdev.dartlang.org (v4).

**Comment by kevmoo** [comment]
>  can we land these v5 changes today?

Yes! (v4 is still default, right? )

**Comment by chalin** [comment]
> Yes! (v4 is still default, right? )

Right.

**Pull request merged**
